---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: web-server

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: web-server

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-server
  labels:
    app.kubernetes.io/name: web-server
spec:
  serviceName: web
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-server
    spec:
      containers:
        - name: web-server
          image: almalinux/9-init
#          image: registry.access.redhat.com/ubi9-init
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - dnf -y install openssh-server && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && echo 'root:root' | chpasswd && /sbin/init
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
